### ISSUE TITLE
Use (advanced) custom fields when analyzing content

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#16]
Don't just analyse the post content but also use the custom fields on the current page. This would be a great feature.

**Comment by lengthofrope** [comment]
It would be able nice to check all textarea's indeed. But it might have some other issues: not all textarea's in ACF fields have to be related to the main content. Going to look at it before 1.0, but not sure if it will make the first release. :P

**Comment by robdekort** [comment]
It would be a great enhancement relative to Yoast. For me the analysis metabox in his current form is useless as no website I ever make has more then 20% of it's page content in the standard post content.

I hear you, basically you need some solution where, as a theme developer, you can assign custom fields for analysis.

**Comment by lengthofrope** [comment]
:+1:

**Comment by lengthofrope** [comment]
It is already working, but only if the wysiwyg editors have been active once, since we are listening to the tinyMCE.on('addEditor') action which is not invoked when the html editor is active.

**Comment by lengthofrope** [comment]
@robdekort Would you like to test the current functionality once you've settled in your new home?

**Comment by robdekort** [comment]
Will do!

**Comment by lengthofrope** [comment]
@robdekort any remarks? :)

**Comment by lengthofrope** [comment]
I assume its working well so closing this issue for now so we can get it released.
