### ISSUE TITLE
Hide metaboxes for some roles or capabilities

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#17]
It would be great if you could hide / show the seo metaboxes for some capabilities defined by the user.

**Comment by lengthofrope** [comment]
Nice one. Will be added before 1.0. Also adding the 'default metabox views' from issue #18.

**Comment by robdekort** [comment]
Great! For example you can toggle that the structured data metabox will only be visible for users having capability 'x'?

**Comment by lengthofrope** [comment]
Yup, it will do something like that. Would be a cool feature.

**Comment by lengthofrope** [comment]
Note: the capabilities wil be to users when upgrading to the not-yet-released 0.11.1 release. So if you would like to run a prerelease make sure you manually add these capabilities.
