### ISSUE TITLE
Save posted content in admin before the loop

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#19]
So you don't need to reload the page in order to see the new seo menu items.

**Comment by lengthofrope** [comment]
The permalinks issue has already been resolved, your suggestion has to do with the way the TAL templating engine works in the plugin. This is something we've got to address before version 1.0. So I'm adding it to the 0.9 milestones

**Comment by lengthofrope** [comment]
Fixed it a little earlier because it was bugging me :P
