### ISSUE TITLE
Disable seo metabox for specific cpt 

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#34]
Enhance the cpt seo settings so you can disable the seo metabox for certain post types.

**Comment by lengthofrope** [comment]
Hey! If a CPT is non-public it won't add the metaboxes. Are there other usescases where it should not be there? After all: if it can be found on the front end, wouldn't you always want to optimize for SEO?

**Comment by robdekort** [comment]
Ah, great. Works as expected. And your right about wanting to optimise if public. Thanks.

**Comment by lengthofrope** [comment]
You're welcome!
