### ISSUE TITLE
Redirection input wanted

### ISSUE THREAD

**Issue by lengthofrope** [nextbuzz/buzz-seo#35]
Ok, so I'm gonna start the Redirection part of the plugin (managing 404 errors and 301 permanent redirects). First I thought of using apache's .htaccess for this, but I think this has two big disadvantages, namely:
- it doesn't on non-apache servers like nginx, which is certainly gaining popularity
- but most of all: apache redirects happen before we can check if a redirect should occur.

**Think of this use case:**
- A user adds a redirect for non-existing slug '/about/partners' and redirects it to '/about'
- The redirect works perfectly and a few weeks go by
- Then some other user creates a page on slug '/about/partners' not realising (or knowing) there is a redirection in effect for that URL. 

Using Apache's .htaccess the redirect supersedes the new page and the partners page is never available. When handling it within the plugin itself, we can identify the page definately exist and ignore or remove the 301 redirect which makes it a lot more managable.

I was thinking to build the redirection part like this:

1. We let WordPress do it's thing and never worry about redirects; until
2. WordPress generates a 404 page.
3. Now we check if the requested page is in the redirection list and if so, redirect it; 
4. if not add it to the 404 list so the users can add their redirections for that URL.

To me this seems like a good idea, but I'm not sure if I'm missing something, so feedback for this workflow is appreciated. @robdekort and @sj0shua

**Comment by robdekort** [comment]
Your arguments for handling the redirects in WP seem valid. As long as you pass a 301 in the head I think this is absolutely the best way to go. Also: .htaccess is ugly ;-)

**Comment by lengthofrope** [comment]
Yeah, main advantage of htaccess is speed. But good to hear it seams to be a valid route in your opinion :P

**Comment by robdekort** [comment]
If we wan't speed we shouldn't use wordpress at all ;-)

**Comment by lengthofrope** [comment]
But we want flexibility as well :+1:
