### ISSUE TITLE
Add visual SEO-status in admin overview pages

### ISSUE THREAD

**Issue by lengthofrope** [nextbuzz/buzz-seo#44]

**Comment by robdekort** [comment]
Please make this optional :-)

**Comment by lengthofrope** [comment]
Definately, hate the feature myself as well ;o)

**Comment by robdekort** [comment]
Yeah, that kind of bloat is the reason I started to dislike Yoast. Would it be possible to somehow make this optional and not on by default for (new) users?

**Comment by lengthofrope** [comment]
We had a lot of debate on this topic earlier this weak and decided in this case it's important for users to be able to see the SEO status. So we will intergrate this in milestone 0.9.0. But I will add a filter for it so it is possible for themes to disable this.
