### ISSUE TITLE
Make CPT meta's (title, description e.d) translatable

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#58]
Currently if you use a multi lingual plugin like Polylang your CPT titles and metadescriptions will be displayed in the default language regarding the language the user is currently browsing your website in. 

It would be nice if you can add the translations for those fields in Polylangs String Translation page. 

https://polylang.wordpress.com/documentation/setting-up-a-wordpress-multilingual-site-with-polylang/strings-translation/ 

And see pll_register_string on: https://polylang.wordpress.com/documentation/documentation-for-developers/functions-reference/

And maybe this for WPML users: https://wpml.org/wpml-hook/wpml_register_string/

**Comment by lengthofrope** [comment]
Het versienummer is nog steeds 0.8.1 dus als 0.8.2 straks uitkomt wordt ie
gewoon geupdate.

2016-05-06 20:39 GMT+02:00 Rob de Kort <notifications@github.com>:
