### ISSUE TITLE
Don't generate language sitemap when using Polylang.

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#61]

**Comment by lengthofrope** [comment]
Hey, I cannot reproduce this issue. I do not see any polylang entries in the sitemap. Can you give me a way to reproduce this?

**Comment by robdekort** [comment]
Can't see it anymore. Perhaps it's been fixed by Polylang?

**Comment by lengthofrope** [comment]
Seems to happen on some sites. I've got an example site at the moment so will try to fix this ASAP.

**Comment by lengthofrope** [comment]
Ok verified this is indeed a polylang bug which was fixed already. If it is still visible on the sitemap, please resave the XML Sitemap options and it will be gone.
