### ISSUE TITLE
Disable seo metabox for specific cpt

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#84]
Enhance the cpt seo settings so you can disable the seo metabox for certain post types. Edge case, but I do have use cases where I want a CPT to be public, but not to have SEO-settings.

See: https://github.com/nextbuzz/buzz-seo/issues/34

**Comment by lengthofrope** [comment]
Hey there,

There's a filter to disable the metabox:

```php
<?php
add_filter('buzz-seo-disable-posttype', function($posttypes) {
    $posttypes[] = 'customposttypeslug';
    return $posttypes;
});
````
